# Generated by Django 3.0.5 on 2020-04-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('campaign_id', models.IntegerField()),
                ('auto_fb_post_mode', models.BooleanField()),
                ('collected_date', models.DateField()),
                ('category_id', models.IntegerField()),
                ('category', models.TextField()),
                ('currencycode', models.TextField()),
                ('current_amount', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('donators', models.IntegerField()),
                ('days_active', models.IntegerField()),
                ('days_created', models.IntegerField()),
                ('title', models.TextField()),
                ('default_url', models.TextField()),
                ('has_beneficiary', models.BooleanField()),
                ('media_type', models.IntegerField()),
                ('project_type', models.IntegerField()),
                ('turn_off_donations', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_first_name', models.TextField()),
                ('user_last_name', models.TextField()),
                ('user_profile_url', models.TextField()),
                ('visible_in_search', models.BooleanField()),
                ('status', models.IntegerField()),
                ('deactivated', models.BooleanField()),
                ('state', models.TextField()),
                ('is_launched', models.BooleanField()),
                ('campaign_image_url', models.TextField()),
                ('created_at', models.DateField()),
                ('launch_date', models.DateField()),
                ('campaign_hearts', models.IntegerField()),
                ('social_share_total', models.IntegerField()),
                ('social_share_last_update', models.DateField()),
                ('location_city', models.TextField()),
                ('location_country', models.TextField()),
                ('location_zip', models.TextField()),
                ('is_charity', models.BooleanField()),
                ('charity_valid', models.BooleanField()),
                ('charity_npo_id', models.IntegerField()),
                ('charity_name', models.TextField()),
                ('velocity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.IntegerField()),
                ('update_id', models.IntegerField()),
                ('collected_date', models.DateField()),
                ('photo_url', models.TextField()),
                ('created_at', models.DateField()),
                ('updates_author', models.TextField()),
                ('updates_author_type', models.TextField()),
                ('updates_text', models.TextField()),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.IntegerField()),
                ('collected_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('is_offline', models.BooleanField()),
                ('is_anonymous', models.BooleanField()),
                ('name', models.TextField()),
                ('created_at', models.DateField()),
                ('profile_url', models.TextField()),
                ('verified', models.BooleanField()),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Campaign')),
            ],
        ),
    ]
