# Generated by Django 3.0.5 on 2020-04-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount_per_donation',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='amt_per_donor_score',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='current_amount_USD',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goalUSD',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location_state',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='percent_of_goal',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='percent_of_goal_score',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='success_Score',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='auto_fb_post_mode',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='charity_valid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='collected_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='deactivated',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='has_beneficiary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_charity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_launched',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='launch_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='social_share_last_update',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='visible_in_search',
            field=models.TextField(),
        ),
    ]
