# Generated by Django 3.0.5 on 2020-04-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200407_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_hearts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='charity_npo_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='current_amount',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='days_active',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='days_created',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='donators',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='media_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='project_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='social_share_total',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='turn_off_donations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='velocity',
            field=models.TextField(),
        ),
    ]
