# Generated by Django 3.0.5 on 2020-04-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200407_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='success_Score',
            new_name='success_score',
        ),
    ]
