# Generated by Django 3.0.5 on 2020-04-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200407_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='collected_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='update',
            name='created_at',
            field=models.TextField(),
        ),
    ]
