# Generated by Django 3.0.5 on 2020-04-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200407_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='collected_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_anonymous',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_offline',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='verified',
            field=models.TextField(),
        ),
    ]
