# Generated by Django 3.0.5 on 2020-04-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_donation_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='verified',
            field=models.TextField(default='default'),
        ),
    ]
