# Generated by Django 3.0.5 on 2020-04-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_donation_donation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='temp_id',
        ),
        migrations.RemoveField(
            model_name='update',
            name='update_id',
        ),
        migrations.AlterField(
            model_name='update',
            name='campaign_id',
            field=models.TextField(),
        ),
    ]
